# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron:  '*/10 * * * *'
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
      lookbackHours:
        description: Lookback Hours
        required: true
        default: "26"
env:
  LOOKBACK_HOURS: "26"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo "Hello ${{ github.event.inputs.name }}"
        echo ${{ github.event.inputs.name || github.event.inputs.name.default }}
      env:
        LOOKBACK_HOURS: ${{ github.event.inputs.lookbackHours }}
        LOOKBACK_HOURS2: ${{ github.event.inputs.lookbackHours || env.LOOKBACK_HOURS }}
