name: Set Outputs

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      # set-output Truncates Multiline Strings. 
      # Docs: 
      # - https://trstringer.com/github-actions-multiline-strings/
      # - https://github.com/actions/toolkit/issues/403
      - name: Set output
        id: set-output
        run: |
          MY_LOG=$(ls -l)
          MY_LOG="${MY_LOG//'%'/'%25'}"
          MY_LOG="${MY_LOG//$'\n'/'%0A'}"
          MY_LOG="${MY_LOG//$'\r'/'%0D'}"
          echo "::set-output name=log::$MY_LOG"

      - name: Verify output
        run: |
          echo ${{ contains(steps.set-output.outputs.log, 'package.json') }}
