name: Set Outputs

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          
      - name: Set output
        id: set-output
        run: echo "::set-output name=log::$(npm i)"

      - name: Get output
        run: echo ${{ steps.set-output.outputs.log }}
