name: Start SSH Server with ngrok

on:
  workflow_dispatch:

jobs:
  setup:
    name: Set up SSH server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: npm install

    - run: npm run shopee >> request.log &

    - name: Start SSH server
      timeout-minutes: 360
      uses: mdelillo/ssh-server-action@v1
      with:
        ngrok-authtoken: "${{ secrets.NGROK_AUTHTOKEN }}"
        ssh-public-key: "${{ secrets.SSH_PUBLIC_KEY }}"